#!/bin/sh
# Build ToME 2.3.11 for the browser (Emscripten + Asyncify).
# Output goes to web/dist; deploy with web/deploy.sh.
set -e
cd "$(dirname "$0")/.."
OUT=web/dist
rm -rf "$OUT" web/stage && mkdir -p "$OUT" web/stage/lib

# The Lua bindings (w_*.c) are generated by tolua in the native build
make -C build -s tome >/dev/null

# Game files: everything but the X11 fonts, sounds, music and BMP tiles.
# lib/user (saves, notes, scores) comes from IndexedDB, not the package.
for d in core dngn edit file help info mods note patch pref scpt cmov; do cp -R lib/$d web/stage/lib/; done
cp lib/module.lua web/stage/lib/
mkdir -p web/stage/lib/data web/stage/lib/save web/stage/lib/apex web/stage/lib/xtra
find web/stage -name 'CMakeLists.txt' -delete
# 16x16.bmp keyed on its "black" pixel -> PNG with alpha (drawn by the page)
python3 -W ignore web/bmp2png.py lib/xtra/graf/16x16.bmp "$OUT/16x16.png"

SRCS=$(sed -n '/^SET(SRCS/,/^)/p' src/CMakeLists.txt | grep -o '[a-z0-9_-]*\.c' \
	| grep -v '^main' | grep -v '^w_' | sed 's|^|src/|')
LUA=$(sed -n '/^ADD_LIBRARY (lua/,/)/p' src/lua/CMakeLists.txt | grep -o '[a-z_]*\.c' | sed 's|^|src/lua/|')

emcc -O2 -fcommon -std=gnu99 -DUSE_WEB -DUSE_PRECISE_CMOVIE -Isrc -Isrc/lua -w \
	$SRCS build/src/w_*.c $LUA src/main.c src/main-web.c \
	-o "$OUT/tome2-core.js" \
	-sASYNCIFY -sASYNCIFY_STACK_SIZE=131072 -sSTACK_SIZE=2097152 \
	-sALLOW_MEMORY_GROWTH -sINITIAL_MEMORY=128MB \
	-sEXPORTED_FUNCTIONS=_main,_web_request_save \
	-sEXPORTED_RUNTIME_METHODS=FS,IDBFS,HEAPU8,addRunDependency,removeRunDependency \
	-sFORCE_FILESYSTEM -lidbfs.js -sENVIRONMENT=web \
	--preload-file web/stage/lib@/tome2/lib

cp web/index.html web/tome2.js "$OUT/"
# Sound effects (lib/xtra/sound, Dubtrain samples) and town music are
# fetched by the page, not preloaded
mkdir -p "$OUT/sound" && cp lib/xtra/sound/*.wav "$OUT/sound/"
cp lib/xtra/sound/Sound.cfg "$OUT/sound/sound.cfg"
mkdir -p "$OUT/music" && cp web/music/new_town.ogg "$OUT/music/"
python3 web/make-help.py > "$OUT/help.html"
rm -rf web/stage
ls -la "$OUT"
